[profile.default]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "reactive-lib/=lib/reactive-lib/"
]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'
bytecode_hash = 'none'

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
